# This is the configuration file for your production environment.
# Typically, you will want to route the traffic through a load balancer
# which adds SSL security through https. If you use Serverpod's standard
# Terraform scripts to deploy your server, all you need to change in
# this file is the flashlistapp.com domain name.

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: api.flashlistapp.com
  publicPort: 443
  publicScheme: https

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: insights.flashlistapp.com
  publicPort: 443
  publicScheme: https

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: app.flashlistapp.com
  publicPort: 443
  publicScheme: https

# Configuration for the database.
database:
  host: postgresql
  port: 5432
  name: serverpod
  user: postgres

# Configuration for the Redis server.
redis:
  enabled: false
  host: redis
  port: 6379
